spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 121314
    url: jdbc:mysql://localhost:3306/wupupupu
  data:
    redis:
      host: localhost
      port: 6379


server:
  port: 8080

